Updation

diff --git a/.github/workflows/nd-shell.yml b/.github/workflows/nd-shell.yml
--- a/.github/workflows/nd-shell.yml
+++ b/.github/workflows/nd-shell.yml
@@ -9,9 +9,6 @@ on:
 env:
   GitHubMail: "manofuranium@gmail.com"
   GitHubName: "ElytrA8"
-  # GH_TOKEN >> Github Personal Access Token << In Repository Secrets
-  # authToken >> Telegram Bot Token << In Repository Secrets
-  # ownerID >> Telegram User/Admin owner ID << In Repository Secrets
 
 jobs:
   ubuntu:
@@ -29,40 +26,26 @@ jobs:
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
 
-      - name: Re-install nodejs and npm
-        run: |
-          sudo apt-get -qq -y install rclone
+      # Cleanup The Actions Workspace Using Custom Composite Run Actions
+      - uses: rokibhasansagar/slimhub_actions@main
 
-      - name: Clone botgram shell-bot repo and Generate config
+      - name: Clone The Secret Mirror Repository
         run: |
-          git clone https://github.com/botgram/shell-bot --depth 1 shell-bot
-          cd shell-bot
-          cat << EOF > config.json
-          {
-            "authToken": "${{ secrets.authToken }}",
-            "owner": ${{ secrets.ownerID }}
-          }
-          EOF
+          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.SOURCE }} source
 
-      - name: Setup Rclone
+      - name: Compile The Mirroring Docker Container
         run: |
-             git clone https://github.com/ElytrA8/rclone
-             mkdir -p /home/runner/.config/rclone
-             mv rclone/rclone.conf /home/runner/.config/rclone
-             rm -rf rclone
-             mkdir /home/runner/drive
-             rclone mount --daemon gdrive:/ /home/runner/drive
-      - name: Install nodejs Dependencies
-        run: |
-          cd shell-bot
-          npm install
+          cd source || exit 1
+          echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
+          docker container prune --force || true
+          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t personal
+          docker image ls
 
-      - name: Run shell-bot server
-        timeout-minutes: 320
+      - name: running Docker
+        timeout-minutes: 340
         continue-on-error: true
         run: |
-          cd shell-bot
-          node server
+          docker run --privileged --rm -i personal
 
       - name: Workflow Looping
         run: |
